import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default:"Roblog Homepage",
    template: "%s | Roblog"
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="container">
      <Navbar/>
      <main className="h-fit">{children}</main>
      <Footer/>
      </div>
      </body>
    </html>
  )
}
